<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.*</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Configurations>Debug;Release;EasyTest</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Model.xafml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Model.xafml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="DevExpress.Drawing.Skia" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Blazor" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Scheduler.Blazor" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Xpo" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.Validation.Blazor" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.StateMachine" Version="25.2.3" />
		<PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" Version="25.2.3" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MINI_CRM_SAMIR_NAKRANI.Module\MINI_CRM_SAMIR_NAKRANI.Module.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="UnusableNodes.xml">
      <DependentUpon>Model.xafml</DependentUpon>
    </None>
  </ItemGroup>
</Project>
